### ISSUE TITLE
作者你好，请问这个项目的分片上传模块是在哪里实现的呢？

### ISSUE THREAD

**Issue by yeweicong** [hss01248/NetWrapper#2]
RT,谢谢

**Comment by hss01248** [comment]
还没有做分片上传的功能 @yeweicong

**Comment by yeweicong** [comment]
@hss01248 接下来会实现吗？我的想法是每次开始上传时requestBody传入文件和offset，根据offset截取文件剩余需要上传的文件的byte[]，然后再赋予真正的requestBody，不知道思路是否正确呢

**Comment by hss01248** [comment]
@yeweicong 分片上传逻辑需要跟服务器端处理策略相配合.而且现在一般都用第三方云存储来管理多媒体资源.
https://my.oschina.net/zhangjie830621/blog/475200?p=1
http://developer.qiniu.com/docs/v6/api/overview/up/chunked-upload.html

这个功能我短期内估计不会去实现,可能到时候写服务端时会对应着写一写.
